///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RX81JenkinsTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RX81JenkinsTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("9abeaefb-13ee-4820-853f-66a77aacee20")]
    public partial class RX81JenkinsTestRepository : RepoGenBaseFolder
    {
        static RX81JenkinsTestRepository instance = new RX81JenkinsTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the RX81JenkinsTestRepository element repository.
        /// </summary>
        [RepositoryFolder("9abeaefb-13ee-4820-853f-66a77aacee20")]
        public static RX81JenkinsTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RX81JenkinsTestRepository() 
            : base("RX81JenkinsTestRepository", "/", null, 0, false, "9abeaefb-13ee-4820-853f-66a77aacee20", ".\\RepositoryImages\\RX81JenkinsTestRepository9abeaefb.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9abeaefb-13ee-4820-853f-66a77aacee20")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class RX81JenkinsTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}